### ISSUE TITLE
Rotation Does Not Work With Two Access Keys

### ISSUE THREAD

**Issue by adamo57** [rhyeal/aws-rotate-iam-keys#20]
Currently, the rotation script does not rotate AWS Access Keys if two keys are found. Is this intended?

**Comment by mmrwoods** [comment]
This is by design. AWS only allows two access keys per IAM user. It is not possible to safely rotate your access key without creating a second key temporarily.

See https://github.com/rhyeal/aws-rotate-iam-keys#caveats
And https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_RotateAccessKey
And https://aws.amazon.com/blogs/security/how-to-rotate-access-keys-for-iam-users/
