### ISSUE TITLE
--profiles <prof1>,<prof2> Not Parsing Correctly

### ISSUE THREAD

**Issue by MikeBourgault** [rhyeal/aws-rotate-iam-keys#37]
In previous versions I haven't had an issue with updating both my default and other profiles in the same line in the ~/.aws-rotate-iam-keys file. I noticed just recently that this is failing with the following error:
```
Rotating keys for profiles: <profile1>,default
Verifying configuration
Verifying credentials
An error occurred (SignatureDoesNotMatch) when calling the ListAccessKeys operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

**Comment by MikeBourgault** [comment]
Is this an issue for anyone else? I'm still running into the same error.

**Comment by rhyeal** [comment]
@MikeBourgault is this occurring on the default profile or another profile? Have you ensured that the secret access key listed is indeed correct? I'm not seeing this on my side and I've got about 5 profiles that rotate daily.

**Comment by mmrwoods** [comment]
@MikeBourgault If you edit `/usr/local/bin/aws-rotate-iam-keys` and add `set -x` on the second line (after `#!/usr/bin/env bash`), then the log file will contain all the commands run by the script.

Run `brew services restart aws-rotate-iam-keys` to re-run the script, and then if you have a look at the log file at `/tmp/homebrew.mxcl.aws-rotate-iam-keys.log` you should see the exact AWS CLI command that failed.

My guess is that the `aws iam list-access-keys` command is failing because it is taking the access key id and secret access key from the first profile listed in the --profiles argument, i.e. `<profile1>`, and that these are wrong somehow (not necessarily wrong in your credentials file, it could be something to do with the code to extract them from the credentials file.

If you try manually running `aws iam list-access-keys --profile <profile1>` does that work?

If you need a quick fix for this, I'd hazard a guess and say if you simply update your `~/.aws-rotate-iam-keys` file and switch the profiles around so it runs `--profiles default,<profile1>` rather than `--profiles <profile1>,default`, it'll probably work fine.

**Comment by MikeBourgault** [comment]
Okay I've tried a few things to no avail, but I think I see the root of the issue here. Not entirely the greatest with bash so excuse my ignorance. It looks like the profiles array is being set with everything up to the first space (in this case: "<profile1>,").

I have attempted to run this explicitly using aws-rotate-iam-keys 1, 2 and this is the output:

```
++ getopt --options=hvfp: --longoptions=force,profile:,profiles:,version,help --name /usr/local/bin/aws-rotate-iam-keys -- --profiles <profile1>, default
+ PARSED=' --profiles '\''<profile1>,'\'' -- '\''default'\'''
+ [[ 0 -ne 0 ]]
+ eval set -- ' --profiles '\''<profile1>,'\'' -- '\''default'\'''
++ set -- --profiles <profile1>, -- default
+ PROFILES=
+ FORCE=
+ true
+ case "$1" in
+ PROFILES=<profile1>,
+ shift 2
+ true
+ case "$1" in
+ shift
+ break
+ [[ -z <profile1>, ]]
+ set -f
+ unset IFS
+ PROFILES_ARR=(${PROFILES//,/ })
+ echo 'Rotating keys for profiles: <profile1>,'

```
Any thoughts?

**Comment by mmrwoods** [comment]
@MikeBourgault In your initial report the pasted output from the script indicated that the `--profiles` option argument was provided without spaces and was parsed correctly as `<profile1>,default`, but in the output above with trace enabled via `set -x` you have a space after `<profile1>,` and before `default`. This means the option argument is read as `<profile1>,`, which is as expected, you'd need to use quotes to allow spaces in the `--profiles` optarg, e.g. `--profiles "foo, bar"`.

Assuming this is not the problem (though if it is, well, hey that's easily fixed, don't use spaces or if you really want to use spaces, wrap the optarg in quotes), have a look in the trace output from the script for lines starting with `aws configure get` and `aws configure set` and lines that set the `ACCESS_KEY_ID` and `SECRET_ACCESS_KEY`. Are the correct profile names being used with `aws configure set/get`, and do you see the correct access key ids and secret access keys being set in the script (these come from reading the configuration, so they should match values in your credentials file at the time it is initially read, i.e. before it is updated when the keys are rotated).

**Comment by MikeBourgault** [comment]
Good catch with the space. That was my bad.

It is working correctly now. 

I definitely had to run it with default,<profile1> rather than <profile1>,default. Also, I can confirm that quotes do work. 

Thanks for all the help @mmrwoods 🎉
