### ISSUE TITLE
Unable to rotate keys with multiple devices

### ISSUE THREAD

**Issue by CodyDunlap** [rhyeal/aws-rotate-iam-keys#51]
I currently have this installed and working on my mac. It works great. But I also have a windows machine that I occasionally have to work from. If I generate an access key for my windows machine to use, this library stops working on my mac. The rotate keys command fails with the following output:

```
Rotating keys for profiles: default
Verifying configuration
Verifying credentials
You have more than 1 access key. Ensure you only have 1 access key and try again.
```

Maybe this can already be done somehow, but I haven't figured out how yet. If there is a way, please share it.

**Comment by mmrwoods** [comment]
@CodyDunlap this is a known limitation, AWS does not allow more than 2 access keys, and in order to rotate keys, you can only have one active access key (the script needs to create and verify a new key before deleting the old key). This is normal practice for IAM key rotation.

It would be nice to find and document a workaround for this problem though. I use multiple devices too, but they are all macbooks, which makes things a lot easier. I run key rotation on my primary macbook, and use SpiderOak to sync the credentials file across all machines (colleagues of mine us Sync.com to do the same). 

However, this isn't going to "just work" when you are mixing unix and windows as the credentials file will be located in a different place, but you could probably work something out by storing a shared credentials file in a sync directory and create symbolic links to it on both windows and mac.

**Comment by RedBlueOrange** [comment]
To work around this issue we are creating and assigning 1 key per device.

**Comment by mmrwoods** [comment]
Closing as this is known limitation with known workarounds, but a PR to update the readme with more info for users wishing to sync credentials across Windows and Nix would be most welcome :-)
